### ISSUE TITLE
Installing in Emacs 29.2 through MELPA fails

### ISSUE THREAD

**Issue by KoltPenny** [purcell/emacs-reformatter#49]
Basically, trying to install this package through MELPA produces the message "Don't Call Me!" in the minibuffer and then fails to install.

**Comment by purcell** [comment]
This must be related to something else in your configuration, since I (and many others) are using the same Emacs version and installing the package from MELPA works just fine.

I see lots of mentions of this error [in relation to emacs-ipython-notebook](https://github.com/search?q=%22Don%27t+Call+Me%21%22+language%3A%22Emacs+Lisp%22+&type=issues), and also [this doom issue](https://github.com/doomemacs/doomemacs/issues/4303) might give you some clues.

I'll close this issue, but feel free to leave further comments if you find out what the problem was.

**Comment by KoltPenny** [comment]
@purcell  Thanks for the heads up. You might be right about the doom thing. Google hasn't been very helpful in that regard lately. I'll look into it and if I figure it out and it's relevant I might leave a comment here if that's ok.

**Comment by purcell** [comment]
Yep, that's okay — good luck!
